services:
  mareena-backend:
    build:
      args:
      - NODE_ENV=development
      context: whizzo-mareena/backend
      target: development
    command: npm run start-watch
    environment:
      - DATABASE_DB=mareena_1
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=mareena-db
      - NODE_ENV=development
    ports:
      - 80:80
      - 9229:9229
      - 9230:9230
    secrets:
      - db-password
    volumes:
      - ./whizzo-mareena/backend/src:/code/src:ro
      - ./whizzo-mareena/backend/package.json:/code/package.json
      - ./whizzo-mareena/backend/package-lock.json:/code/package-lock.json
      - back-notused:/opt/app/node_modules
    networks:
      - public
      - private
    depends_on:
      - mareena-db
  mareena-db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
      - ./whizzo-mareena/db/init:/initialiase-db
#    entrypoint:
#      - sh -c "cd /initialise-db"
    # exposing port locally 
    ports:
      - 3306:3306
    networks:
      - private
      - public
    environment:
      - MYSQL_DATABASE=mareena_1
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
  mareena-frontend:
    build:
      context: whizzo-mareena/frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./whizzo-mareena/frontend/src:/code/src
      - /code/node_modules
    networks:
      - public
    depends_on:
      - mareena-backend
  mareena-worker:
    build: whizzo-worker/whizzo-worker
    secrets:
      - db-password
    environment:
      - DATABASE_DB=mareena_1
      - DATABASE_USER=root
      - DATABASE_PASSWORD_FILE=/run/secrets/db-password
      - DATABASE_HOST=mareena-db
      - DATABASE_PORT=3306
    ports:
      - 8080:8080
    networks:
      - public
      - private
    depends_on:
      - mareena-backend
    #profiles:
    #  - donotstart


networks:
  public:
  private:
volumes:
  back-notused:
  db-data:
secrets:
  db-password:
    file: whizzo-mareena/db/password.txt
